invoice_project/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import main_page
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', main_page)
    path('', include('invoices.urls', namespace='invoices')),
]



#THIS IS FOR MEDIA HANDLING FOLLOWING THE SETTINGS IN SETTINGS.PY
# urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

#this is to change the header of the app 
admin.site.site_header = "Invoice Admin System"
admin.site.index_title = "Management"

invoices/urls.py
from .views import (
    InvoiceListView,
    InvoiceFormView,
    InvoiceUpdateView,
    AddPositionsFormView,
    CloseInvoiceView,
    InvoicePositionsDeleteView,
    invoice_pdf_view,
)
from django.urls import path

app_name = 'invoices'
urlpatterns = [
    path('', InvoiceListView.as_view(), name = 'main'),
    path('new/', InvoiceFormView.as_view(), name = 'create'),
    # path('<pk>/', SimpleTemplateView.as_view(), name = 'simple_template'),
    path('<pk>/', AddPositionsFormView.as_view(), name = 'detail'),
    path('<pk>/close/', CloseInvoiceView.as_view(), name = 'close'),
    path('<pk>/update/', InvoiceUpdateView.as_view(), name = 'update'),
    path('<pk>/pdf/', invoice_pdf_view, name="pdfs"),
    path('<pk>/delete/<int:position_pk>/', InvoicePositionsDeleteView.as_view(), name = 'position-delete'),
]

invoices/models.py
from django.db import models
from django.dispatch import receiver
from profiles.models import Profile
from receivers.models import Receiver


# Create your models here.

class Tag(models.Model):
    name            = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)

class Invoice(models.Model):
    profile         = models.ForeignKey(Profile, on_delete=models.CASCADE)
    receiver        = models.ForeignKey(Receiver, on_delete=models.CASCADE)
    number          = models.CharField(max_length=10, blank=True)
    completion_date = models.DateField()
    issue_date      = models.DateField()
    payment_date    = models.DateField()
    created         = models.DateTimeField(auto_now=True)

    #if closed - hide add positions and unable to add new ones
    closed          = models.BooleanField(default=False)
    tags            = models.ManyToManyField(Tag, blank=True)


    def __str__(self):
        return f"Invoice number: {self.number}, pk:{self.pk}"
        

    @property
    def tags(self):
        return self.tags.all()

    @property
    def positions(self):
        return self.positions_set.all()

    @property
    def total_amount(self):
        total   = 0
        qs      = self.positions
        for pos in qs:
            total += pos.amount

        return "{:,}".format(total)

  

invoices/forms.py
from random import random
from django import forms
from django.core.exceptions import ValidationError
from .models import Invoice
from profiles.utils import generate_invoice_number



class InvoiceForm(forms.ModelForm):
    completion_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Real Completion Date')
    issue_date      = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    payment_date    = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    
    
    class Meta:
        model = Invoice
        fields = (
            'receiver', 
            'number', 
            'completion_date', 
            'issue_date', 
            'payment_date'
            )
        labels = {#dates cannot be changed here
                'receiver': 'Customer'
                

            }

    def clean_number(self):
        number = self.cleaned_data.get('number')
        # if len(number) < 5:
        #     raise ValidationError('Number is too short')
        if number == "":
            number = generate_invoice_number()
        return number
        

        

invoices/views.py
import profile
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, 
    FormView, 
    TemplateView, 
    DetailView, 
    UpdateView,
    RedirectView,
    DeleteView,
)
from django.urls import reverse
from invoices.forms import InvoiceForm
from positions.models import Positions
from .models import Invoice
from profiles.models import Profile
from django.views.generic import View
from django.contrib import messages
from positions.forms import PositionForm
from .mixins import InvoiceNotClosedMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.

class InvoiceListView(ListView):
    model           = Invoice
    template_name   = "invoices/main.html" #default invoice_list.html
    paginate_by     = 4
    context_object_name = 'qs'

    def get_queryset(self):
        #profile = Profile.objects.get(user=self.request.user) #this is an alternative for get_object_or_404
        profile = get_object_or_404(Profile, user = self.request.user)
        # qs = Invoice.objects.filter(profile = profile).order_by('-created')
        #qs = Invoice.objects.all().order_by('-created')  #This is used to output all the invoices
        # return qs

        return super().get_queryset().filter(profile = profile).order_by('-created') #this is an alternative for returning qs

#this class lets user create a new form 
class InvoiceFormView(LoginRequiredMixin, FormView):
    form_class      = InvoiceForm
    template_name   = 'invoices/create.html'
    # success_url     = reverse_lazy('invoices:main') #this will return the form to main view after successfull completion of a new form
    i_instance      = None


    def get_success_url(self):
        return reverse('invoices:detail', kwargs={'pk': self.i_instance.pk})


    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        instance = form.save(commit=False)
        instance.profile = profile
        form.save()
        self.i_instance = instance
        return super().form_valid(form)

class SimpleTemplateView(LoginRequiredMixin, DetailView):
    model = Invoice
    template_name = 'invoices/detail.html'

#this is used to replace the success_url (user is redirected here after a save)
# class SimpleTemplateView(TemplateView):
#     template_name = 'invoices/simple_template.html'


class AddPositionsFormView(LoginRequiredMixin, FormView): #this is to add positions to the invoice
    form_class      = PositionForm
    template_name   = 'invoices/detail.html'
   
    def get_success_url(self):
        return self.request.path

    def form_valid(self, form):
        invoice_pk       = self.kwargs.get('pk')
        invoice_obj      = Invoice.objects.get(pk = invoice_pk)
        instance         = form.save(commit=False)
        instance.invoice = invoice_obj
        form.save()
        messages.info(self.request, f'successfully added position - {instance.title}')
        return super().form_valid(form)

    #in class based view- this method is used to pass message to the template (get_context_data)
    def get_context_data(self, **kwargs):
        context         = super().get_context_data(**kwargs)
        invoice_obj     = Invoice.objects.get(pk=self.kwargs.get('pk'))
        qs              = invoice_obj.positions
        context['obj']  = invoice_obj
        context['qs']   = qs    
        return context


#I used the function created in mixins.py here to protect user from deleting using the path
class InvoiceUpdateView(LoginRequiredMixin, InvoiceNotClosedMixin, UpdateView):
    model = Invoice
    template_name = 'invoices/update.html'
    form_class = InvoiceForm
    success_url = reverse_lazy('invoices:main')

    #this function is used to display the alert message after update is done
    def form_valid(self, form):
        instance = form.save()
        messages.info(self.request, f'Successfully updated invoice - {instance.number}')
        return super().form_valid(form)



class CloseInvoiceView(LoginRequiredMixin, RedirectView):
    pattern_name = "invoices:detail"


    def get_redirect_url(self, *args, **kwargs):
        pk          = self.kwargs.get('pk')
        obj         = Invoice.objects.get(pk = pk)
        obj.closed  = True
        obj.save()
        return super().get_redirect_url(*args, **kwargs)



#I used the function created in mixins.py here to protect user from deleting using the path
class InvoicePositionsDeleteView(LoginRequiredMixin, InvoiceNotClosedMixin, DeleteView):
    model = Positions
    template_name = 'invoices/position_confirm_delete.html'

    #/<pk>/delete/<position_pk>/
    def get_object(self):
        pk = self.kwargs.get('position_pk')
        obj = Positions.objects.get(pk = pk)
        return obj


    def get_success_url(self):
        messages.info(self.request, f'Deleted Position -{self.object.title}' )
        return reverse('invoices:detail', kwargs={'pk': self.object.invoice.id})


#imports for xhtml2pdf
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders

@login_required
def invoice_pdf_view(request, **kwargs):

    pk = kwargs.get('pk')
    obj = Invoice.objects.get(pk=pk)

    logo_result = finders.find('img/logo.png')
    font_result = finders.find('fonts/Lato-Regular.ttf')
    # shows search location results
    searched_locations = finders.searched_locations
    print(searched_locations)

    template_path = 'invoices/pdf.html'
    context = {
        'object': obj,
        'static': {
            'font': font_result,
            'logo': logo_result,
        },

    }
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="invoice.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html.encode('utf-8'), dest=response, encoding='utf-8')

    # if case of error
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

invoices/templates/invoices/create.html
{% extends "index.html" %} {% load crispy_forms_tags %} {% block title %} New Invoice {% endblock title %} {% block content %}

<form action="" method="POST">
    {% csrf_token %} {{ form | crispy }}


    <button type="submit" class="btn btn-primary">save</button>
</form>

{% endblock content %}

invoices/templates/invoices/detail.html
{% extends "index.html" %} {% load crispy_forms_tags %} {% block title %} details page {% endblock title %} {% block content %}



<!-- add position Modal -->
<div class="modal fade" id="addPositionsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Positions</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST">
                    {% csrf_token %} {{form|crispy}}
                    <button type="submit" class="btn btn-primary mt-3">Save</button>




                </form>
            </div>
        </div>
    </div>
</div>

<!-- close invoice Modal -->
<div class="modal fade" id="closeInvoiceModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to close the invoice?
            </div>
            <div class="modal-footer">
                <a href="{% url 'invoices:close' obj.pk %}" class="btn btn-secondary">Close</a>

            </div>
        </div>
    </div>
</div>

<div>


    <div>
        {% if not obj.closed %}

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPositionsModal">
                + Add Positions
            </button>
        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#closeInvoiceModal">
                Close
            </button> {% else %}
        <a href="{% url 'invoices:pdfs' obj.pk %}" class="btn btn-danger">pdf</a> {% endif %}

    </div>

    <!-- Modal -->












    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save Changes</button>
                </div>
            </div>
        </div>
    </div>






    {% if messages %} {% for message in messages %} {% if message.tags == 'info' %}
    <div class="alert alert-primary mt-2">
        {{message}}
    </div>
    {% endif %} {% endfor %} {% endif %}
    <div class="mt-3">
        <h5>Receiver: {{obj.receiver.name}}</h5>
        <hr>
        <h3>Positions</h3>
        {% if qs %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for item in qs %}
                <tr style="vertical-align: middle;">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{item.title}}</td>
                    <td>{{item.description}}</td>
                    <td>{{item.amount}}</td>

                    <td>
                        {% if not obj.closed %}
                        <a href="{% url 'invoices:position-delete' obj.pk item.pk %}" class="btn btn-danger">X</a> {% else %} closed {% endif %}

                    </td>


                </tr>
                {% endfor %}

            </tbody>
        </table>

        <div class="mt-2 text-end">
            <h2>Total Amount: N {{obj.total_amount}}</h2>

        </div>

        {% else %}
        <h5>No Positions added...</h5>
        {% endif %}
    </div>
    {% endblock content %}

invoices/templates/invoices/main.html
{% extends "index.html" %} {% block title %} Home {% endblock title %} {% block content %} {% if messages %} {% for message in messages %} {% if message.tags == 'info' %}
<div class="alert alert-primary mt-2">
    {{message}}
</div>
{% endif %} {% endfor %} {% endif %} {% if qs %} {% for obj in qs %}
<div class="card mb-2" style="width: 100%">
    <div class="card-body">
        <h5 class="card-title">{{obj.number}} - {{obj.receiver.name}}</h5>
        <div class="card-text">completion_date: {{obj.completion_date}}</div>
        <div class="text-muted">Amount N {{obj.total_amount}}</div>
        <div class="mt-2">

            <a href="{% url 'invoices:detail' obj.pk %}" class="btn btn-primary">Details</a> {% if not obj.closed %}
            <a href="{% url 'invoices:update' obj.pk %}" class="btn btn-info">Update</a> {% endif %}
        </div>
    </div>
</div>
{% endfor %} {% else %}
<h3>No Invoices created ...</h3>
{% endif %} {% if is_paginated %}
<nav aria-label="invoice pagination">
    <ul class="pagination">
        <li class="page-item {% if page_obj.has_previous %} {% else %} disabled {% endif %}">
            <a {% if page_obj.has_previous %} href="?page={{page_obj.previous_page_number}}" {% endif %} class="page-link" tabindex="-1" aria-disabled="true">Previous</a>
        </li>

        {% for i in paginator.page_range %}
        <li class="page-item {% if page_obj.number == i %} active {% endif %}">
            <a class="page-link" href="?page={{i}}">{{i}}</a>
        </li>
        {% endfor %}


        <li class="page-item {% if page_obj.has_next %} {% else %} disabled {% endif %}">
            <a {% if page_obj.has_next %} href="?page={{page_obj.next_page_number}}" {% endif %} class="page-link">Next</a>
        </li>
    </ul>
</nav>

{% endif %} {% endblock content %}

invoices/templates/invoices/pdf.html
<!DOCTYPE html>

<html>

<head>
    <title>Invoice | PDF</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        body {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }
        
        footer {
            margin-top: auto;
        }
        
        @page {
            size: a4 portrait;
            margin: 2cm;
        }
        
        @font-face {
            font-family: 'Lato';
            src: url({{static.font}});
        }
        
        * {
            font-family: 'Lato';
            font-size: 12px;
        }
        
        table {
            border-collapse: collapse;
            border: 1px solid #e8e8e8;
        }
        
        .site-footer {
            background-color: #737373;
            padding: 45px 0 20px;
            font-size: 15px;
            line-height: 24px;
            color: #29aafe;
        }
        
        .site-footer hr {
            border-top-color: #bbb;
            opacity: 0.5
        }
        
        .site-footer a {
            color: #737373;
        }
        
        .site-footer a:hover {
            color: #3366cc;
            text-decoration: none;
        }
        
        .footer-links {
            padding-left: 0;
            list-style: none
        }
        
        .footer-links li {
            display: block
        }
        
        .footer-links a {
            color: #737373
        }
        
        .footer-links a:active,
        .footer-links a:focus,
        .footer-links a:hover {
            color: #3366cc;
            text-decoration: none;
        }
        
        .footer-links.inline li {
            display: inline-block
        }
        
        .site-footer .social-icons {
            text-align: right
        }
        
        .site-footer .social-icons a {
            width: 40px;
            height: 40px;
            line-height: 40px;
            margin-left: 6px;
            margin-right: 0;
            border-radius: 100%;
            background-color: #33353d
        }
        
        .copyright-text {
            margin: 0
        }
    </style>
</head>

<body>
    <section id="header-section">
        <table style="width: 100%; border: 0px">
            <tr>
                <th style="text-align: left; width: 25%">
                    <img src="static/img/logo.png" width="100">
                </th>

                <th style="text-align: right">
                    <br>
                    <div style="font-size: 14px;"> Invoice number : {{object.number}}<br> Completion Date : {{object.completion_date}}<br> Issue Date : {{object.issue_date}}<br> Payment Date : {{object.payment_date}}<br><br>
                        <div>Account Number : {{object.profile.account_number}} </div>
                    </div>
                </th>

            </tr>
        </table>
        <hr>
        <br>
        <table style="width: 100%">
            <th style="text-align: left">
                <div style="font-size: 15px"> Sender:</div>
                {{object.profile.company_name}}<br>

            </th>
            <th style="text-align: left">
                <div style="font-size: 15px"> Receiver:</div>
                {{object.receiver.name}}<br> {{object.receiver.address}}
                <br> {{object.receiver.website}}
                <br>
            </th>
        </table>
    </section>
    <br>
    <section id="data-section">
        {% if object.positions %}
        <h3>Positions</h3>
        <table style="width: 100%; margin-top: 20px;">
            <tr style="background-color: #e8e8e8; ">
                <th style="text-align: left; width: 5%;">#</th>
                <th style="text-align: left">Title</th>
                <th style="text-align: left">Description</th>
                <th style="text-align: left">Amount</th>
            </tr>
            {% for position in object.positions %}

            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{position.title}}</td>
                <td>{{position.description}}</td>
                <td>N {{position.amount}}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h3>No positions added</h3>
        {% endif %}
        <div style="font-size: 15px; margin-top: 10px; text-align: right">Total: N {{object.total_amount}}</div>

    </section>
    <hr>
    <hr>
    <br>
    <section id="header-section">
        <table style="width: 100%; border: 0px">
            <tr>
                <th style="text-align: right; width: 25%">

                </th>

                <th style="text-align: right">
                    <br>
                    <div><img src="static/img/bukolasignature.png" width="100"> </div>
                </th>

            </tr>
        </table>
        <hr>
        <br>

    </section>
    <br>
    <section id="data-section">

        <hr>
        <br>
        <!-- Site footer -->
        <footer class="site-footer">

            <div class="container" style=" text-align: center">
                <div class="row">
                    <div class="col-md-8 col-sm-6 col-xs-12">
                        <p class="copyright-text" style="color: #29aafe;">Copyright &copy; 2022 All Rights Reserved by
                            <a href="https://tpais-events.com/">TPAIS Nig Ltd</a>.
                        </p>
                        <p class="copyright-text" style="color: #29aafe;">19, Cairo Street, Wuse II, Abuja</p>
                        <p class="copyright-text" style="color: #29aafe;">
                            <a href="https://tpais-events.com/"></a>www.tpais-events.com | contactus@tpais-events.com</p>
                    </div>

                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <ul class="social-icons">
                            <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        </footer>


</body>

</html>

invoices/templates/invoices/pdfs.html
<!DOCTYPE html>

<html>

<head>
    <title>Invoice | PDF</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        body {
            margin-top: 10px;
            background: #eee;
        }
    </style>
</head>

<body>
    <div class="container bootdey">
        <div class="row invoice row-printable">
            <div class="col-md-10">
                <!-- col-lg-12 start here -->
                <div class="panel panel-default plain" id="dash_0">
                    <!-- Start .panel -->
                    <div class="panel-body p30">
                        <div class="row">
                            <!-- Start .row -->
                            <div class="col-lg-6">
                                <!-- col-lg-6 start here -->
                                <div class="invoice-logo"><img width="100" src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Invoice logo"></div>
                            </div>
                            <!-- col-lg-6 end here -->
                            <div class="col-lg-6">
                                <!-- col-lg-6 start here -->
                                <div class="invoice-from">
                                    <ul class="list-unstyled text-right">
                                        <li>Dash LLC</li>
                                        <li>2500 Ridgepoint Dr, Suite 105-C</li>
                                        <li>Austin TX 78754</li>
                                        <li>VAT Number EU826113958</li>
                                    </ul>
                                </div>
                            </div>
                            <!-- col-lg-6 end here -->
                            <div class="col-lg-12">
                                <!-- col-lg-12 start here -->
                                <div class="invoice-details mt25">
                                    <div class="well">
                                        <ul class="list-unstyled mb0">
                                            <li><strong>Invoice</strong> #936988</li>
                                            <li><strong>Invoice Date:</strong> Monday, October 10th, 2015</li>
                                            <li><strong>Due Date:</strong> Thursday, December 1th, 2015</li>
                                            <li><strong>Status:</strong> <span class="label label-danger">UNPAID</span></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="invoice-to mt25">
                                    <ul class="list-unstyled">
                                        <li><strong>Invoiced To</strong></li>
                                        <li>Jakob Smith</li>
                                        <li>Roupark 37</li>
                                        <li>New York, NY, 2014</li>
                                        <li>USA</li>
                                    </ul>
                                </div>
                                <div class="invoice-items">
                                    <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th class="per70 text-center">Description</th>
                                                    <th class="per5 text-center">Qty</th>
                                                    <th class="per25 text-center">Total</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>1024MB Cloud 2.0 Server - elisium.dynamic.com (12/04/2014 - 01/03/2015)</td>
                                                    <td class="text-center">1</td>
                                                    <td class="text-center">$25.00 USD</td>
                                                </tr>
                                                <tr>
                                                    <td>Logo design</td>
                                                    <td class="text-center">1</td>
                                                    <td class="text-center">$200.00 USD</td>
                                                </tr>
                                                <tr>
                                                    <td>Backup - 1024MB Cloud 2.0 Server - elisium.dynamic.com</td>
                                                    <td class="text-center">12</td>
                                                    <td class="text-center">$12.00 USD</td>
                                                </tr>
                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <th colspan="2" class="text-right">Sub Total:</th>
                                                    <th class="text-center">$237.00 USD</th>
                                                </tr>
                                                <tr>
                                                    <th colspan="2" class="text-right">20% VAT:</th>
                                                    <th class="text-center">$47.40 USD</th>
                                                </tr>
                                                <tr>
                                                    <th colspan="2" class="text-right">Credit:</th>
                                                    <th class="text-center">$00.00 USD</th>
                                                </tr>
                                                <tr>
                                                    <th colspan="2" class="text-right">Total:</th>
                                                    <th class="text-center">$284.4.40 USD</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                                <div class="invoice-footer mt25">
                                    <p class="text-center">Generated on Monday, October 08th, 2015 <a href="#" class="btn btn-default ml15"><i class="fa fa-print mr5"></i> Print</a></p>
                                </div>
                            </div>
                            <!-- col-lg-12 end here -->
                        </div>
                        <!-- End .row -->
                    </div>
                </div>
                <!-- End .panel -->
            </div>
            <!-- col-lg-12 end here -->
        </div>
    </div>

</body>

</html>

invoices/templates/invoices/position_confirm_delete.html
{% extends "index.html" %} { % load crispy_forms_tags %} {% block title %} delete position {% endblock title %} {% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete <b>"{{object.title}}"</b> ?</p>
    <button type="submit" class="btn btn-primary">yes</button>





</form>


{% endblock content %}

invoices/templates/invoices/simple_template.html
{% extends "index.html" %} {% block title %} Invoices {% endblock title %} {% block content %} {{object.pk}} - {{object.number}} {% endblock content %}