invoice_project/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import main_page
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', main_page)
    path('', include('invoices.urls', namespace='invoices')),
]



#THIS IS FOR MEDIA HANDLING FOLLOWING THE SETTINGS IN SETTINGS.PY
# urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

#this is to change the header of the app 
admin.site.site_header = "Invoice Admin System"
admin.site.index_title = "Management"

invoices/urls.py
from .views import (
    InvoiceListView,
    InvoiceFormView,
    InvoiceUpdateView,
    AddPositionsFormView,
    CloseInvoiceView,
    InvoicePositionsDeleteView,
    invoice_pdf_view,
)
from django.urls import path

app_name = 'invoices'
urlpatterns = [
    path('', InvoiceListView.as_view(), name = 'main'),
    path('new/', InvoiceFormView.as_view(), name = 'create'),
    # path('<pk>/', SimpleTemplateView.as_view(), name = 'simple_template'),
    path('<pk>/', AddPositionsFormView.as_view(), name = 'detail'),
    path('<pk>/close/', CloseInvoiceView.as_view(), name = 'close'),
    path('<pk>/update/', InvoiceUpdateView.as_view(), name = 'update'),
    path('<pk>/pdf/', invoice_pdf_view, name="pdfs"),
    path('<pk>/delete/<int:position_pk>/', InvoicePositionsDeleteView.as_view(), name = 'position-delete'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- favicon-->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- custom css-->
    <link rel="stylesheet" href="{% static 'style.css' %}"> {% block scripts %} {% endblock scripts %}

    <title>Invoice App | {% block title %} {% endblock title %}</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container mt-3">
        {% block content %} {% endblock content %}

    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

</body>

</html>

templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- favicon-->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- custom css-->
    <link rel="stylesheet" href="{% static 'style.css' %}"> {% block scripts %} {% endblock scripts %}

    <title>Invoice App | {% block title %} {% endblock title %}</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container mt-3">
        {% block content %} {% endblock content %}

    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

</body>

</html>

templates/navbar.html
<nav class="navbar navbar-dark bg-primary">
    <div class="container">
        <a href="{% url 'invoices:main' %}" class="navbar-brand">Invoice App</a>
        <a href="{% url 'invoices:create' %}" class="btn btn-outline-light">+New</a>
        <a href="https://www.tpais-events.com" class="btn btn-outline-light">Home</a>
    </div>
</nav>